### ISSUE TITLE
Doubt about mapping the ideConnector servlet in web.xml

### ISSUE THREAD

**Issue by D612** [mediaworx/opencms-ideconnector#8]
I'm trying to use the plugin with OpenCms 11. I checked the registration and I have only exclude information in the web.xml doesn't have the mapping information that needs to be configured for the ideConnector servlet to work. I tested the cmisatom call and it worked, the ideConnector servlet error 404 error, I realized that the configuration of the servlet and servlet-mapping is missing, I am several weeks trying to solve this, there is no documentation, if you can, please send an example of the configuration in the web.xml to make the ideConnector call work, thank you very much for any help.

**Comment by kaiwidmann** [comment]
Hey D612,

there should be no Servlet configuration necessary, the Servlet is configured in the class itself with an annotation like this:
```
@WebServlet(
		name = "ideConnector",
		urlPatterns = {"/ideConnector/*"}
)
public class IDEConnectorService extends javax.servlet.http.HttpServlet {
```
But the Servlet has to be added to the List of additionalExcludePrefixes. There's some documentation on how to configure this here: https://github.com/mediaworx/opencms-intellijplugin/wiki/2-Installation#installing-the-ide-connector

I hope this works for you, but we've also experienced problems with the ideConnector not being found in current versions of OpenCms and IntelliJ. Unfortunately I didn't have time to look into it yet. I'll let you know as soon as I have a fix, but I can't give you any time frame, sorry.

Best

Kai

**Comment by kaiwidmann** [comment]
I poked around and found out that the problem doesn't seem to be the servlet itself, but the IntelliJ plugin. What happens if you call http://localhost:8080/ideConnector/login (assuming you app runs on 8080) in your browser? You should get a JSON error message like this (maybe in english): 

`{"loggedIn":false,"message":"ERROR logging in to OpenCms: Benutzer \"null\" würde nicht gefunden..\n StackTrace available in the OpenCms log file.","token":null}`

If you get this error you know that your servlet is working just fine. There seems to be some problem in the plugin, I'll see what I can find out about this next.

**Comment by kaiwidmann** [comment]
Hey there, 

I've traced the problem to an incompatibility of a newer version of Jackson that was introduced with a GitHub pull request. I've fixed the problem, a new version of the IntelliJ plugin is already submitted to the JetBrains plugin repository and should be available shortly. 

If you want to use OpenCms 11, you'll also need to update tha IDE connector module to version 2.1, since there was also a breaking change in the manifest generation of OpenCms 11 that had to be taken care of. You'll finde a download link here: 
https://github.com/mediaworx/opencms-intellijplugin/wiki/2-Installation#installing-the-ide-connector

Please let me know if the updated plugin and the updated connector module solved your problems.

Best

Kai

**Comment by kaiwidmann** [comment]
I just saw that it might take two days until the new version of the plugin is available through the JetBrains plugin repository. Let me know if you need the plugin faster, then I'll send you the zip.

**Comment by D612** [comment]
Thank you very much Kai, I made a video for you to understand the processes that I make. See if there is any fault of mine.  I'm running tests with Java 1.8, but I'll need to use OpenJDK 11. But first I'm trying to work with Java 1.8.

Video (change for 1080p): https://www.youtube.com/watch?v=9Bh3kiM3HAg 

I go test with the new plug-in (jetbrains), avaliable! and the connector. Thank you in advance for your help!

Kind Regards,

Deiverson

**Comment by D612** [comment]
WORK! See the evidence: https://www.youtube.com/watch?v=cF5xI58RUPA
Now I'm going to test with OpenJDK 11 to see if there will be any problems! 

Thank you very much!

**Comment by kaiwidmann** [comment]
Hey Deiverson, 

the call to /system/modules/com.mediaworx.opencms.ideconnector/test.html shows that the jsp connector is working. It's not possible to call system/modules/com.mediaworx.opencms.ideconnector/connector.jsp directly, it's normal, that the response is a blank page. As for the ideConnector servlet, it also can't be called directly (a blank page is normal here as well), but you can call ideConnector/login, then you should see a JSON response (not logged in). If you see this, both the JSP connector and the servlet are working properly. 

If this doesn't help, you can send me your IntelliJ log (prefarably right after you called the "Sync Module" action).

Best

Kai

**Comment by D612** [comment]
WORK! \o/ See the new evidence (test sync): https://www.youtube.com/watch?v=cF5xI58RUPA

I update plugin intelliJ (1.11) and connector (2.1) in OpenCms. Now I'm going to test with OpenJDK 11 to see if there will be any problems!

Thank you very much! \o/

Best,

Deiverson

**Comment by D612** [comment]
Hi Kai, unfortunately the problem fixed in version 11.0.1 happened again in version 11.0.2, exactly the same things.

**Comment by kaiwidmann** [comment]
He Deiverson, 

what happens if you call /system/modules/com.mediaworx.opencms.ideconnector/test.html? Do you get the expected responses once you submit the form?
Unfortunately I won't have the time to analyze that problem right away, I'd have to set up an OpenCms 11.0.2 instance first, since I'm still not working with OpenCms 11.

Cheers, Kai
